name: Deploy Laravel Octane

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mbstring, xml, bcmath, curl, zip, intl, oci8
          coverage: none

      - name: Create Production .env file
        uses: jasonmccreary/dotfiles@master
        with:
          env-id: production
          content: |
            ${{ secrets.DOT_ENV_PRODUCTION }}
            DB_URL="${{ secrets.DB_URL_PRODUCTION }}"

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader --no-progress --no-interaction

      - name: Deploy via SSH to Oracle Cloud
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/laravel

            git fetch origin
            git reset --hard origin/main

            php artisan config:clear
            php artisan route:clear

            cat << 'EOF' > .env
            ${{ env.production }}
            EOF

            composer install --no-dev --optimize-autoloader

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            php artisan migrate --force
            php artisan octane:reload
