name: Deploy Laravel Octane

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mbstring, xml, bcmath, curl, zip, intl, oci8
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader --no-progress --no-interaction

      - name: Deploy via SSH to Oracle Cloud
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22

          envs: DB_URL_PROD
          script: |
            cd /var/www/laravel

            # 1. Alinha o código do servidor com o GitHub
            git fetch origin
            git reset --hard origin/main

            # 2. Limpa os caches antigos para não ler lixo na memória
            php artisan config:clear
            php artisan route:clear

            # 3. CRIAÇÃO NATIVA E BLINDADA DO .ENV (Sem plugins)
            # O 'EOF' em aspas simples impede o Bash de quebrar com os parênteses da Oracle
            cat << 'EOF' > .env
            ${{ secrets.DOT_ENV_PRODUCTION }}
            DB_URL="$DB_URL_PROD"
            EOF

            # 4. Atualiza os pacotes internos do projeto
            composer install --no-dev --optimize-autoloader

            # 5. Compila as novas configurações em cache
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # 6. Roda o banco e recarrega os workers do Octane
            php artisan migrate --force
            php artisan octane:reload
        env:
          DB_URL_PROD: ${{ secrets.DB_URL_PRODUCTION }}
